# dbt Core – layers: dl (bronze) → stg (transformations) → dw (data warehouse) → dm (business)
name: "data_tools"
version: "1.0.0"
profile: "data_tools"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  environment: "dev"
  dim_date_start: "2010-01-01"
  dim_date_end: "2030-12-31"

models:
  data_tools:
    bronze:    # dl_* – data lake / landing (tables from raw)
      +schema: bronze
      +materialized: view
    stg:       # stg_* – transformation views
      +schema: staging
      +materialized: view
    silver:    # dw_fact_* / dw_dim_* – data warehouse (facts & dimensions)
      +schema: silver
      +materialized: view
    gold:      # dm_* – business / data marts
      +schema: gold
      +materialized: table
