# dbt Core – layers:
#   landing: SOURCE only (Parquet in MinIO, no dbt models)
#   bronze:  stg reads from landing, → Iceberg tables
#   silver:  dw reads from bronze → Iceberg tables
#   gold:    dm reads from silver → Iceberg tables
name: "data_tools"
version: "1.0.0"
profile: "data_tools"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  environment: "dev"
  dim_date_start: "2010-01-01"
  dim_date_end: "2030-12-31"

models:
  data_tools:
    # Bronze: stg reads from landing source → Iceberg tables (Dremio/MinIO)
    # +schema per layer → minio.bronze, minio.silver, minio.gold (siblings, not nested)
    bronze:
      +schema: bronze
      +materialized: table
      +post-hook: []  # Iceberg via dbt-dremio
    # Silver: data warehouse → Iceberg tables
    silver:
      +schema: silver
      +materialized: table
    # Gold: data marts → Iceberg tables
    gold:
      +schema: gold
      +materialized: table
