# dbt Core – layered (spine) model:
#   landing: SOURCE only (Parquet in MinIO)
#   bronze:  staging (stg_*) → Iceberg
#   silver:  warehouse (dw_*) → Iceberg
#   gold:    marts (dm_*) → Iceberg
# Tags: env via target; layer/model tags for selection (e.g. dbt run --select tag:bronze)
name: "data_tools"
version: "1.0.0"
profile: "data_tools"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  environment: "dev"  # Override with --vars '{"environment": "prod"}' or per target
  dim_date_start: "2010-01-01"
  dim_date_end: "2030-12-31"

models:
  data_tools:
    bronze:
      +schema: bronze
      +materialized: table
      +tags: [bronze, staging, layer_bronze]
      +post-hook: []
    silver:
      +schema: silver
      +materialized: table
      +tags: [silver, warehouse, layer_silver]
    gold:
      +schema: gold
      +materialized: table
      +tags: [gold, mart, layer_gold]
