version: 2
sources:
  # Landing: Parquet files from MinIO (mysql_to_landing DAG)
  # Path: s3://landing/mimdbuat01/{plants|licenses}/data.parquet
  # Dremio: promote folders plants/licenses as Parquet (Format as dataset) in minio→landing→mimdbuat01
  - name: landing
    description: Landing layer – Parquet files in MinIO (MySQL → landing via Airflow)
    database: "{{ env_var('LANDING_DATABASE', 'minio') }}"
    schema: "{{ env_var('LANDING_SCHEMA', 'landing.mimdbuat01') }}"
    tables:
      - name: plants
        description: Plant records from MySQL mimdbuat01.plants (Parquet)
        schema: "{{ env_var('LANDING_SCHEMA', 'landing.mimdbuat01') }}.plants"
        identifier: data.parquet
        columns:
          - name: id
            tests: [not_null]
          - name: updated_at
            tests: [not_null]
      - name: licenses
        description: License records from MySQL mimdbuat01.licenses (Parquet)
        schema: "{{ env_var('LANDING_SCHEMA', 'landing.mimdbuat01') }}.licenses"
        identifier: data.parquet
        columns:
          - name: id
            tests: [not_null]
          - name: updated_at
            tests: [not_null]
